### ISSUE TITLE
Specify a transparent method of curation for posts

### ISSUE THREAD

**Issue by Etiene** [Etiene/lua.space#13]
When should we decide not to merge a PR? 
Why? 
How do we approach this? 
How to respond to a denied PR without demotivating the person?

halp

**Comment by cauefcr** [comment]
I suggest clear directions for the blog, by having a clear goal of what should or shouldn't be discussed in the blog that could be used as a Rule book of sorts, so that contributions would not have problems of ambiguities and personal preferences in accepting pull requests.

**Comment by karai17** [comment]
I think this blog should promote the use of Lua, explain some common and uncommon uses of Lua, encourage experimentation with Lua such as using it in places that it is not commonly used (web dev, Raspberry Pi, etc). I also think this Blog should not become dogmatic in that it chastises other languages and claims Lua is the only real option. As much as we can all agree that PHP sucks, this blog probably isn't the right medium to promote that idea. Keep things positive, etc.

In that regard, I think this blog should allow a somewhat relaxed approach to content in that we can welcome many posts from many topics and viewpoints. But I don't think we should be too lax in that the quality of posts becomes poor. I suspect that this blog is going to be an English blog, so posts should be well written using proper spelling and grammar. If a person wants to write a post but English is not their primary language, it could be beneficial for them to have someone proof read their forked post by opening an issue here requesting a proof, and accept PRs to their own fork before sending a PR here. This would ensure all posts read well, have good structure, and would not discourage anyone from wanting to contribute.

**Comment by karai17** [comment]
It would also be great to provide constructive criticism and encouragement to someone who sends a PR that is not acceptable. Maybe there is something they can do to improve their post to bring it up to snuff instead of having it silently rejected. If the whole post just doesn't fit the blog's goals, a detailed explanation why that is the case would benefit the author so that they can rethink their post and resubmit a new one.

**Comment by Etiene** [comment]
How does this sound? http://lua.space/general/contributing-to-lua-space

**Comment by undefdev** [comment]
Really sorry I'm joining this discussion so late.
Somehow this got lost under the radar for me!

I think your post is really nice and positive, good job!
I only think there's one thing we should add as well.

I think we shouldn't accept blog posts that misrepresent Lua!
For example, there shouldn't be code in blog posts that suggests limitations in Lua that don't exist.
This kind of code is often written by programmers mainly experienced in programming languages that have those limitations.

One of Lua's major advantage compared to other languages is its flexibility.
Not making use of features like multiple return values, dynamic typing or flexibility of tables when reasonable, could shine a bad light on Lua and even promote bad code in the ecosystem.

Of course not everybody has to be a programming wizard, and there are always different styles and approaches, but if the author doesn't take Lua seriously (really takes a closer look at the language) we could lose credibility with Lua nerds interested in the blog.

**Comment by mpeterv** [comment]
@undefdev that seems overly protective. If a post contains some inefficient or unidiomatic code, just comment on it, that way not only the author will learn something new, but the readers as well.

**Comment by Etiene** [comment]
@mpeterv I tend to agree with that, either we comment on the PR or on the post itself :) I think that will depend on how we feel about the post as a whole as well. If there's many things to be addressed, I think it's best to comment on the PR, if there's not many, on the comment section of the post after published.

I think it's nice to see activity at the comment section! :) For example, on this post by @zot24: http://lua.space/webdev/oauth2-authentication-with-lua#disqus_thread I thought the post was awesome but it lacked some more benchmarking info. Since that was the only thing I had to comment on the post, I specifically decided to publish as is and ask it later :) The author replied on the comments and I think this creates engagement :dancers:  

The same could be applied to code snippets, I believe

**Comment by undefdev** [comment]
I just mean that this should be discussed in the pull request, just like orthography, grammar and content.
So people know what to expect when making a pull request.

**Comment by karai17** [comment]
I agree with @undefdev here. If someone writes an article and their code
examples are poor quality, it would be ideal to discuss the PR instead of
publishing and revising. Someone trying to force Lua to work like another
language and producing poor quality results is something I would like to
avoid promoting.

**Comment by zot24** [comment]
I think a mix of both approaches is the best option - you'll need a discussion on the PR as we did to solve somethings, including maybe poor code examples. I have basically just started with Lua so my code could be not the best example, however it's a valuable example of a real life usage. Then of course the comment on Disqus is good as well, because it will give you more visibility when new users come to the web site as they will see activity on that blog and that will encourage them to participate.

**Comment by karai17** [comment]
Discussion within an article probably shouldn't be about quality of code, though. Discussing the ideas presented, asking for help, discussion other ways to do the thing, these are all useful topics of discussion. Having people argue over Lua idioms (or lack thereof) would be unpleasant discussion and would turn people away.

**Comment by Etiene** [comment]
There's also a question of what exactly is "code that could be improved" or "poor code".  If we are assholes on PRs we will scare writers off too xD 

Maybe we should write some posts about specific Lua advantages first, so we can give the reference? :) 

Generally, I think achieving consensus on case-by-case also works :) It will depend on who is available sooner to review and comment but I don't think this will have negative consequences. I don't like letting PRs rotting for too long if it's seemingly ready to go, because otherwise some readers can just read it on github before everyone else xD But how do we organize that so it's not completely random?

**Comment by karai17** [comment]
I think there is a fairly clear difference between code that could be touched up and code that sucks. If the person in question is writing code that just doesn't comply with any Lua standards or ignores clear Lua features, and instead feels more like someone is brute forcing Lua to act more like C or Ruby or whatever, then it's probably not an article we want to host without serious considerations. If the code is more-or-less fine but could be improved by adding one or two things, then that should be fine. We can give the author feedback in the PR and then publish it.

I don't want to be some protectionist or elitist jerk by any means, but every language has its culture and idioms and we should strive to meet those when it makes sense, and break them when it makes sense. It's definitely something that should be looked at on a case-by-case basis. If a person is promoting their library and wants everyone to see how awesome it is, it would be nice it it fit in with what is expected of Lua. If someone hacked together some novel or amusing script and feels like sharing it for kicks, we probably don't need to scrutinize it so much.

**Comment by mpeterv** [comment]
Sure, but do we need an explicit rule that says "Don't post code that sucks?"

**Comment by karai17** [comment]
As both Etiene and I said, it's probably best to deal with low quality on a case-by-case basis. It might be a good idea to explain some general expectations such as "use Lua's advantages where possible" or what have you, but I honestly don't think it is going to be a problem.

Someone wanting to contribute to a Lua community blog is likely a fan of Lua, and writes code that at least resembles idiomatic Lua. I doubt we're going to see many disgruntled PHP or C developers contributing their brute forced Lua code.

I think most of this discussion can be summed up as "we'll cross that bridge when we get to it".

**Comment by Etiene** [comment]
I guess we can consider this discussion closed? :)

**Comment by undefdev** [comment]
I suppose so.

undef

_Indie Game Developer_

_www.quadrantgame.com
http://www.quadrantgame.comhttps://twitter.com/undefdev
https://twitter.com/undefdev_

2016-02-17 17:19 GMT+07:00 Etiene Dalcol notifications@github.com:
