### ISSUE TITLE
Should we have categories that do not show on the first page by default?

### ISSUE THREAD

**Issue by Etiene** [Etiene/lua.space#14]
Example of use case: a category for posts in other languages

**Comment by karai17** [comment]
I was definitely going to suggest this. Perhaps another level in the tree structure for i18n support would allow this blog to be displayed in many different languages without clogging up the feed. There should probably be a way to see which languages the post supports and the ability to click through to another language.

```
+-------------------------------------------+
en | fr | pr | de

Blog Post Title

blah blah blah
+-------------------------------------------+
```
