### ISSUE TITLE
Add archive page

### ISSUE THREAD

**Issue by josefnpat** [Etiene/lua.space#17]
I regularly find myself on the page and I don't subscribe to the RSS feed, so I often have no idea what articles I've missed.

Can we add an archive page that list lists all the articles titles?

_p.s. big fan, awesome blog_

**Comment by Etiene** [comment]
Thank you!! Consider this suggestion accepted!  :+1:

**Comment by Etiene** [comment]
Done <3

**Comment by josefnpat** [comment]
:+1: :heart:
