### ISSUE TITLE
Content Suggestions?

### ISSUE THREAD

**Issue by karai17** [Etiene/lua.space#19]
Would it be a good idea to create a list of topics or potential article ideas that could give new authors some direction to create their first article? Personally, I believe I am pretty decent at writing, but coming up with a topic to write about can be difficult.

A second note, I have written several Lua modules and I was wondering if it would be considered taboo or shameless self promotion to write about them. They are all free and open source.

**Comment by Etiene** [comment]
Hey!! Yes, I'll try to elaborate a list with potential topics.

Also, writing about a module or library you made yourself is completely ok!  :D It's nice though to set a tone that is not just an announcement or promotion, such as tutorial on how to use your tool or comparison with other tools, use cases etc.

**Comment by karai17** [comment]
Yeah, I don't really care much to market my modules so much as make it known what tools are out there. Things I've created tend to exist because there were no other options, or other options were abandoned. I'll see if I can't write up a few gamedev articles over the next little while. :)
