### ISSUE TITLE
Front page previews

### ISSUE THREAD

**Issue by karai17** [Etiene/lua.space#22]
Currently, the front page lists five whole articles. That is a lot of content for one page. Maybe it would be better to only display the first paragraph or two on the front page and require the user to click through to see a full article. This would make navigating much faster for the user.

**Comment by rm-code** [comment]
I'd like to see this as well :+1:

**Comment by Etiene** [comment]
Ok!! I will get my hands on that after vacations unless someone wants to go ahead :) :+1:
