### ISSUE TITLE
Job section

### ISSUE THREAD

**Issue by Etiene** [Etiene/lua.space#23]
Would a section to post Lua-related job positions be more appropriate at lua.space or luarocks.org?

**Comment by ThaisRobba** [comment]
I'd say it would be more appropriate at lua.space, since it is a bit of a "all things Lua".

**Comment by undefdev** [comment]
I also think it would be great to have at lua.space, but not on the landing page.

**Comment by Etiene** [comment]
Ok! It's decided! A job section will come in :) But no time to work on that yet unless someone wants to go ahead :)

**Comment by Etiene** [comment]
@undefdev I've been planning to add a link at the menu that takes to the job area :)

**Comment by undefdev** [comment]
Awesome! :D

undef

_Indie Game Developer_

_www.quadrantgame.com
http://www.quadrantgame.comhttps://twitter.com/undefdev
https://twitter.com/undefdev_

2016-02-05 16:58 GMT+07:00 Etiene Dalcol notifications@github.com:

**Comment by Etiene** [comment]
Hey! So... a minimum viable product of the job section is there :)

Now... a small question, maybe we should find a way to better advertise the jobs posted! How? Do we open a twitter account and create a small bot? Do we add them to the rss? Do we add a separate rss so people can subscribe to specifically to offers?

**Comment by undefdev** [comment]
Awesome! :D
Maybe we should have a twitter bot for Lua.space altogether!

undef

_Indie Game Developer_

_www.quadrantgame.com
http://www.quadrantgame.comhttps://twitter.com/undefdev
https://twitter.com/undefdev_

2016-02-10 2:26 GMT+07:00 Etiene Dalcol notifications@github.com:

**Comment by daurnimator** [comment]
Close this issue now it's available?

**Comment by Etiene** [comment]
A discussion is still going on :)

**Comment by ThaisRobba** [comment]
:+1: 

I'm in favor of a small twitter bot + a hacker news post when this gets a bit of traction + showcasing this in the lua reddit and mailing list.

A bot for lua.space sounds good, not sure a separate bot only for jobs would be needed.

**Comment by Etiene** [comment]
Right now we don't have enough content so a bot is necessary, but I've created our twitter account and I'm posting things manually: https://twitter.com/space_lua

I'll consider this topic closed then! :)
