### ISSUE TITLE
(scientific) books

### ISSUE THREAD

**Issue by markuman** [Etiene/lua.space#27]
today I've made a discovery by accident while searching for lua in a mathematically field.

http://link.springer.com/book/10.1007/978-1-4020-9920-5
"Numerical Methods for Nonlinear Engineering Models"

Take a look the the "Front Matter", chapter 2.2 "Lua as a Programming Language".
Or take a look at "Numerical Fundamentals and Computer Programming" -> "Look inside" -> last break: 

> Of all these scripting languages, the language with the fastest execution speed
> is Lua and because of this it is finding increasing applications in computer games.
> Lua also probably has the simplest and most straightforward syntax and the sim-
> plest data structure as only one data type, a table, is supported by the native lan-
> guage. ...

Of source not the cheapest book. But what about creating a book section?

**Comment by Etiene** [comment]
What exactly should go in a book section? Reviews of books?

**Comment by markuman** [comment]
...if someone is willing to write a review, then yes (I've never read a book about Lua until now). 
Or an overview what's available (and up to date) or what the book is addressing (basic, gaming, science...)
and maybe w/o partner link to funding lua/lua.space/support the community?

**Comment by Etiene** [comment]
Oh! You mean that if we have a section listing Lua related books and someone buys them through our page we could use that as a way to fund more community stuff?

**Comment by markuman** [comment]
it might work, or may not ...

**Comment by Etiene** [comment]
I don't see why not trying, specially if everyone agrees that's fine x) I was just trying to understand if that's really the suggestion :) I'll investigate how referrals like those work and in the meantime others can comment what they think :)

**Comment by undefdev** [comment]
Do you know a lot of Lua books that are recommendable?
Apart from programming in Lua I haven't read anything, and if our book
section would only consist of books we don't know about it's a bit strange.

I don't think that these kind of referral links would be a viable source of
income anyway, how many people do you expect to buy books through
Lua.space, and how much do you guys think we would get for each sale?

I think the job section is way more promising, and should be focused on for
now.

undef

_Indie Game Developer_

_www.quadrantgame.com
http://www.quadrantgame.comhttps://twitter.com/undefdev
https://twitter.com/undefdev_

2016-02-02 4:08 GMT+07:00 Etiene Dalcol notifications@github.com:
