### ISSUE TITLE
Question about suitability of a blog post

### ISSUE THREAD

**Issue by createuniverses** [Etiene/lua.space#37]
Recently I've used Lua in my live coding tool praxis to play with and study OpenGL shaders. I've recently written up this experience in a couple of blog posts. These posts walk the reader through what was created as part of these studies.

https://createuniverses.wordpress.com/2016/04/22/some-shadertoy-examples/
https://createuniverses.wordpress.com/2016/05/10/a-text-editor-in-a-shader/

Would these be appropriate entries for Lua.Space?

**Comment by undefdev** [comment]
Hey there!

Even though this looks kind of cool, I think it's not what people are looking for on a Lua centered blog.
Nothing about your posts is really Lua specific and your posts rather show the capabilities of your tool.

I think some people on reddit eg. /r/gamedev might be interested in that code though, especially the one about the text editor, so I'd encourage you to share it there.

Cheers,

undef

**Comment by createuniverses** [comment]
Thank you for your reply. Even though Lua code completely governs the loading and running of the shaders, you're right that the post doesn't focus on the Lua side much at all except for a couple of one line glimpses. It focusses more on how the OpenGL API was used to accomplish the result. Perhaps if I talked about how Lua was helpful with the rapid prototyping and how it allowed me to try out things quickly, the post might have been more appropriate.

It was a long shot posting this question, but I thought I'd ask. Thank you again.
